//! Umbrella crate for authoring loadable-node plugins.
//!
//! Plugins should depend on this single crate and re-export everything they
//! need: the wire-format types, the trait surface, and the FFI plumbing.
//! Plan reference: `docs/plans/2026-05-14-skinny-traits-dual-emit-plugins.md`.

pub use abi_stable;
pub use async_ffi;
pub use inventory;
pub use loadable_node_abi::{
    FfiNode, FfiNodeBox, FfiNodeFactory, FfiNodeFactoryBox, FfiNodeFactory_TO, FfiNode_TO,
    NodePlugin, NodePluginRef, OutputSink, OutputSinkBox, OutputSink_TO,
};
pub use remotemedia_traits as traits;
pub use remotemedia_types as types;
pub use rmp_serde;

pub mod adapter;
pub mod params;

#[cfg(feature = "python-plugin")]
pub mod python_subprocess;

#[cfg(feature = "python-plugin")]
pub mod python_ipc;

#[cfg(feature = "python-plugin")]
pub mod control_hook;

/// Inventory entry describing one loadable-export factory.
///
/// Generated by the `#[node]` proc-macro under
/// `#[cfg(feature = "loadable-export")]`. Plugin crates that link
/// `remotemedia-plugin-sdk` and call [`plugin_export!()`] (no-arg form)
/// walk the inventory at startup and register every factory the crate
/// compiled in.
///
/// `make` is an `extern "Rust"` function pointer (not a closure) so the
/// `inventory::submit!` value is `const`-constructible.
pub struct LoadableFactoryEntry {
    /// Constructor for one [`FfiNodeFactoryBox`]. The macro emits a
    /// named `fn` per node and stores its pointer here.
    pub make: fn() -> FfiNodeFactoryBox,
}

inventory::collect!(LoadableFactoryEntry);

/// Expand to the abi_stable root-module boilerplate for a loadable plugin.
///
/// Two forms:
///
/// * **No-argument** — walks `inventory::iter::<LoadableFactoryEntry>()`
///   and registers every factory the `#[node]` macro emitted under
///   `#[cfg(feature = "loadable-export")]`. Recommended for plugins that
///   author their nodes with the `#[node]` macro.
///
///   ```ignore
///   remotemedia_plugin_sdk::plugin_export!();
///   ```
///
/// * **Explicit type list** — pass one or more [`FfiNodeFactory`] types
///   (one per node the plugin exposes). Each factory must implement
///   [`Default`] so the macro can `<$factory>::default()` instantiate
///   it. Useful when authoring nodes by hand without the `#[node]`
///   macro, or to override the inventory-driven set.
///
///   ```ignore
///   remotemedia_plugin_sdk::plugin_export!(MyFactoryA, MyFactoryB);
///   ```
///
/// Both forms expand to:
/// - a `#[sabi_extern_fn]` `__remotemedia_list_factories` that builds an
///   `RVec<FfiNodeFactoryBox>`, and
/// - a `#[export_root_module]` returning a [`NodePluginRef`] whose
///   `list_factories` field points at the function above.
#[macro_export]
macro_rules! plugin_export {
    () => {
        #[$crate::abi_stable::sabi_extern_fn]
        fn __remotemedia_list_factories()
            -> $crate::abi_stable::std_types::RVec<$crate::FfiNodeFactoryBox>
        {
            let mut v = $crate::abi_stable::std_types::RVec::new();
            for entry in $crate::inventory::iter::<$crate::LoadableFactoryEntry>() {
                v.push((entry.make)());
            }
            v
        }

        #[$crate::abi_stable::export_root_module]
        fn __remotemedia_root_module() -> $crate::NodePluginRef {
            use $crate::abi_stable::prefix_type::PrefixTypeTrait;
            $crate::NodePlugin {
                list_factories: __remotemedia_list_factories,
            }.leak_into_prefix()
        }
    };
    ($($factory:ty),+ $(,)?) => {
        #[$crate::abi_stable::sabi_extern_fn]
        fn __remotemedia_list_factories()
            -> $crate::abi_stable::std_types::RVec<$crate::FfiNodeFactoryBox>
        {
            let mut v = $crate::abi_stable::std_types::RVec::new();
            $(
                v.push($crate::FfiNodeFactory_TO::from_value(
                    <$factory as ::core::default::Default>::default(),
                    $crate::abi_stable::sabi_trait::TD_Opaque,
                ));
            )+
            v
        }

        #[$crate::abi_stable::export_root_module]
        fn __remotemedia_root_module() -> $crate::NodePluginRef {
            use $crate::abi_stable::prefix_type::PrefixTypeTrait;
            $crate::NodePlugin {
                list_factories: __remotemedia_list_factories,
            }.leak_into_prefix()
        }
    };
}

/// Expand to a complete loadable Python-plugin definition.
///
/// One macro call replaces ~50 lines of plumbing: registers a
/// [`python_subprocess::PythonSubprocessFactory`] against a caller-
/// supplied embedded directory under the given `node_type`, and emits
/// the abi_stable root module the host `LoadableNodeBundle::load()`
/// consumes — equivalent in author effort to the Rust-side
/// [`plugin_export!`].
///
/// # Required keys
///
/// * `node_type` — string literal matching the pipeline's `node_type:`
///   for this node (e.g. `"MossTTSRealtimeNode"`).
/// * `module` — bare Python module name to import in the runner (e.g.
///   `"moss_tts_realtime"`). Resolved against the extracted directory
///   via `--module-root`.
/// * `class` — Python class name within the module. Currently
///   informational (runner looks up by `node_type`) but reserved.
/// * `embedded` — expression returning a `&'static include_dir::Dir<'static>`.
///   The author invokes [`include_dir::include_dir!`] directly (proc
///   macros can't be re-exported through `remotemedia-plugin-sdk`, so
///   the author owns the call site).
///
/// # Example
///
/// ```ignore
/// use include_dir::{include_dir, Dir};
///
/// static EMBED: Dir<'_> = include_dir!("$CARGO_MANIFEST_DIR/embedded");
///
/// remotemedia_plugin_sdk::python_plugin_export! {
///     node_type: "MossTTSRealtimeNode",
///     module:    "moss_tts_realtime",
///     class:     "MossTTSRealtimeNode",
///     embedded:  &EMBED,
/// }
/// ```
///
/// Available only when the `python-plugin` cargo feature is enabled.
/// The plugin crate must add `include_dir = "0.7"` to its own
/// `[dependencies]` since proc-macro re-exports are not supported.
#[cfg(feature = "python-plugin")]
#[macro_export]
macro_rules! python_plugin_export {
    {
        node_type: $node_type:literal,
        module:    $module:literal,
        class:     $class:literal,
        embedded:  $embedded:expr $(,)?
    } => {
        fn __remotemedia_py_plugin_factory()
            -> $crate::FfiNodeFactoryBox
        {
            $crate::python_subprocess::PythonSubprocessFactory::boxed(
                $crate::python_subprocess::PythonPluginConfig {
                    node_type: $node_type,
                    module:    $module,
                    class:     $class,
                    embedded:  $embedded,
                },
            )
        }

        // Surface the factory through the same inventory mechanism the
        // Rust-side `#[node(loadable_export)]` path uses, so a single
        // `plugin_export!()` call below picks both kinds up uniformly.
        $crate::inventory::submit! {
            $crate::LoadableFactoryEntry {
                make: __remotemedia_py_plugin_factory,
            }
        }

        // Emit the abi_stable root module. Identical to the no-arg form
        // of `plugin_export!()` — both walk the inventory.
        $crate::plugin_export!();
    };
}
